#include "iostream"
#include "cstdlib"
#include <string>
#include <vector>
#include <TH2.h> 
#include <TChain.h>

class EvtInfoBranches {
public:


    //Declaration of leaves types

   // Declaration of leaf types
   Double_t        PU_nTrueInt;
   Int_t           PU_nPUVert;
   Int_t           EvtInfo_EventNum;
   Int_t           EvtInfo_RunNum;
   Int_t           EvtInfo_LumiSection;
   Int_t           EvtInfo_BunchXing;
   Int_t           EvtInfo_NumVtx;
   vector<double>  *EvtInfo_VertexX_;
   vector<double>  *EvtInfo_VertexY_;
   vector<double>  *EvtInfo_VertexZ_;
   Double_t        ptHat_;
   Double_t        mcWeight_;
   vector<double>  *genParE_;
   vector<double>  *genParPt_;
   vector<double>  *genParEta_;
   vector<double>  *genParPhi_;
   vector<double>  *genParM_;
   vector<int>     *genParQ_;
   vector<int>     *genParId_;
   vector<int>     *genParSt_;
   vector<int>     *genMomParId_;
   vector<int>     *genParIndex_;
   vector<int>     *genNMo_;
   vector<int>     *genNDa_;
   vector<int>     *genMo1_;
   vector<int>     *genMo2_;
   vector<int>     *genDa1_;
   vector<int>     *genDa2_;
   vector<double>  *genJetE_;
   vector<double>  *genJetPt_;
   vector<double>  *genJetEta_;
   vector<double>  *genJetPhi_;
   Double_t        NumMu;
   vector<double>  *patMuonPt_;
   vector<double>  *patMuonEta_;
   vector<double>  *patMuonPhi_;
   vector<double>  *patMuonM_;
   vector<double>  *patMuonSumTrkPt_;
   vector<double>  *patMuonTrkIso_;
   vector<double>  *patMuonHcalIso_;
   vector<double>  *patMuonEcalIso_;
   vector<double>  *patMuonCharge_;
   vector<double>  *patMuonNumChambers_;
   vector<double>  *patMuonNumMatches_;
   vector<double>  *patMuonStationMask_;
   vector<double>  *patMuonNumSegments_;
   vector<double>  *patMuonChi2Ndoff_;
   vector<double>  *patMuonNhits_;
   vector<double>  *patMuonQoverP_;
   vector<double>  *patMuonTheta_;
   vector<double>  *patMuonLambda_;
   vector<double>  *patMuonDxy_;
   vector<double>  *patMuonD0_;
   vector<double>  *patMuonDsz_;
   vector<double>  *patMuonDs_;
   vector<double>  *patMuonDxyBS_;
   vector<double>  *patMuonDzBS_;
   vector<double>  *patMuonDszBS_;
   vector<double>  *patMuonVx_;
   vector<double>  *patMuonVy_;
   vector<double>  *patMuonVz_;
   vector<double>  *patMuonGenMatchPt_;
   vector<double>  *patMuonGenMatchEta_;
   vector<double>  *patMuonGenMatchPhi_;
   vector<double>  *patMuonGenMotherId_;
   vector<double>  *patMuonGenMatchCharge_;
   vector<double>  *patMuonChHadSumPt03_;
   vector<double>  *patMuonNeHadSumPt03_;
   vector<double>  *patMuonGamSumPt03_;
   vector<double>  *patMuonChHadSumPt04_;
   vector<double>  *patMuonNeHadSumPt04_;
   vector<double>  *patMuonGamSumPt04_;
   vector<double>  *patMuonChHadSumPt05_;
   vector<double>  *patMuonNeHadSumPt05_;
   vector<double>  *patMuonGamSumPt05_;
   vector<double>  *fastJetRho_;
   vector<double>  *PFchsJetRho_;
   vector<double>  *lepIsoRho_;
   vector<double>  *patElecEt_;
   vector<double>  *patElecEnergy_;
   vector<double>  *patElecPt_;
   vector<double>  *patElecEta_;
   vector<double>  *patElecPhi_;
   vector<double>  *patElecM_;
   vector<double>  *patElecScEn_;
   vector<double>  *patElecScEt_;
   vector<double>  *patElecScEta_;
   vector<double>  *patElecScPhi_;
   vector<double>  *patElecisEcalDriven_;
   vector<double>  *patElecisTrackerDriven_;
   vector<double>  *patElecSigIhIh_;
   vector<double>  *patElecDelEtaIn_;
   vector<double>  *patElecDelPhiIn_;
   vector<double>  *patElecHoE_;
   vector<double>  *patElecTrkIso_;
   vector<double>  *patElecHcalIso_;
   vector<double>  *patElecEcalIso_;
   vector<double>  *patElecCharge_;
   vector<double>  *patElecRelIsoComb_;
   vector<double>  *patElecDxy_;
   vector<double>  *patElecD0_;
   vector<double>  *patElecDsz_;
   vector<double>  *patElecDz_;
   vector<double>  *patElecDxyBS_;
   vector<double>  *patElecDszBS_;
   vector<double>  *patElecDzBS_;
   vector<double>  *patElecMva_;
   vector<double>  *patElecChHadSumPt03_;
   vector<double>  *patElecNeHadSumPt03_;
   vector<double>  *patElecGamSumPt03_;
   vector<double>  *patElecChHadSumPt04_;
   vector<double>  *patElecChHadIso_;
   vector<double>  *patElecNeHadIso_;
   vector<double>  *patElecGamIso_;
   vector<double>  *patElecNeHadSumPt04_;
   vector<double>  *patElecGamSumPt04_;
   vector<double>  *patElecChHadSumPt05_;
   vector<double>  *patElecNeHadSumPt05_;
   vector<double>  *patElecGamSumPt05_;
   vector<double>  *patElecMissingHits_;
   vector<double>  *patElecDist_;
   vector<double>  *patElecDeltaCotTheta_;
   vector<double>  *patElecConvRadius_;
   vector<double>  *patElecInBarrel_;
   vector<double>  *patElecInEndcap_;
   vector<double>  *JetPt_;
   vector<double>  *JetEta_;
   vector<double>  *JetPhi_;
   vector<double>  *JetM_;
   vector<double>  *JetEn_;
   vector<double>  *JetCharMulti_;
   vector<double>  *JetNeutEmEFr_;
   vector<double>  *JetCharHadEFr_;
   vector<double>  *JetNeutHadEFr_;
   vector<double>  *JetCharEmEFr_;
   Double_t        eleRho;
   Double_t        muoRho;
   Double_t        metSig;
   vector<double>  *higgsPt;
   vector<double>  *higgsEta;
   vector<double>  *higgsPhi;
   vector<double>  *higgsM;
   vector<double>  *higgsMRefit;
   vector<double>  *zllPt;
   vector<double>  *zllEta;
   vector<double>  *zllPhi;
   vector<double>  *zllM;
   vector<double>  *zlldR;
   vector<double>  *zjjPt;
   vector<double>  *zjjEta;
   vector<double>  *zjjPhi;
   vector<double>  *zjjM;
   vector<double>  *zjjMRefit;
   vector<double>  *zjjdR;
   vector<int>     *HjetIndex;
   vector<int>     *HjetHiggsIndex_;
   vector<double>  *HjetE;
   vector<double>  *HjetPt;
   vector<double>  *HjetEta;
   vector<double>  *HjetPhi;
   vector<int>     *LeptonsIndex;
   vector<int>     *LeptonsHiggsIndex_;
   vector<double>  *LeptonsE;
   vector<double>  *LeptonsPt;
   vector<double>  *LeptonsEta;
   vector<double>  *LeptonsPhi;
   vector<double>  *LeptonsType;
   vector<double>  *heliLD;
   vector<double>  *costhetaNT1;
   vector<double>  *costhetaNT2;
   vector<double>  *phiNT;
   vector<double>  *phiNT1;
   vector<double>  *costhetastarNT;
   vector<double>  *heliLDRefit;
   vector<double>  *costhetaNT1Refit;
   vector<double>  *costhetaNT2Refit;
   vector<double>  *phiNTRefit;
   vector<double>  *phiNT1Refit;
   vector<double>  *costhetastarNTRefit;
   vector<int>     *nBTags;
   vector<int>     *lepType;
   vector<int>     *passBit;


   vector<double>  *JetNConstituents_;
   vector<int>     *JetGenPartonID_;
   vector<double>  *JetGenPartonEn_;
   vector<double>  *JetGenPartonPt_;
   vector<double>  *JetGenPartonEta_;
   vector<double>  *JetGenPartonPhi_;
   vector<int>     *JetGenPartonStatus_;
   vector<int>     *JetGenPartonU3ID_;
   vector<int>     *JetGenPartonU2ID_;
   vector<int>     *JetGenPartonU1ID_;
   vector<int>     *JethasGenParton_;
  

  vector<int>  *patElecID_;
  vector<int>  *patMuonID_;






   void Register(TTree *Analysis) {


   // Set object pointer
   EvtInfo_VertexX_ = 0;
   EvtInfo_VertexY_ = 0;
   EvtInfo_VertexZ_ = 0;
   genParE_ = 0;
   genParPt_ = 0;
   genParEta_ = 0;
   genParPhi_ = 0;
   genParM_ = 0;
   genParQ_ = 0;
   genParId_ = 0;
   genParSt_ = 0;
   genMomParId_ = 0;
   genParIndex_ = 0;
   genNMo_ = 0;
   genNDa_ = 0;
   genMo1_ = 0;
   genMo2_ = 0;
   genDa1_ = 0;
   genDa2_ = 0;
   genJetE_ = 0;
   genJetPt_ = 0;
   genJetEta_ = 0;
   genJetPhi_ = 0;
   patMuonPt_ = 0;
   patMuonEta_ = 0;
   patMuonPhi_ = 0;
   patMuonM_ = 0;
   patMuonSumTrkPt_ = 0;
   patMuonTrkIso_ = 0;
   patMuonHcalIso_ = 0;
   patMuonEcalIso_ = 0;
   patMuonCharge_ = 0;
   patMuonNumChambers_ = 0;
   patMuonNumMatches_ = 0;
   patMuonStationMask_ = 0;
   patMuonNumSegments_ = 0;
   patMuonChi2Ndoff_ = 0;
   patMuonNhits_ = 0;
   patMuonQoverP_ = 0;
   patMuonTheta_ = 0;
   patMuonLambda_ = 0;
   patMuonDxy_ = 0;
   patMuonD0_ = 0;
   patMuonDsz_ = 0;
   patMuonDs_ = 0;
   patMuonDxyBS_ = 0;
   patMuonDzBS_ = 0;
   patMuonDszBS_ = 0;
   patMuonVx_ = 0;
   patMuonVy_ = 0;
   patMuonVz_ = 0;
   patMuonGenMatchPt_ = 0;
   patMuonGenMatchEta_ = 0;
   patMuonGenMatchPhi_ = 0;
   patMuonGenMotherId_ = 0;
   patMuonGenMatchCharge_ = 0;
   patMuonChHadSumPt03_ = 0;
   patMuonNeHadSumPt03_ = 0;
   patMuonGamSumPt03_ = 0;
   patMuonChHadSumPt04_ = 0;
   patMuonNeHadSumPt04_ = 0;
   patMuonGamSumPt04_ = 0;
   patMuonChHadSumPt05_ = 0;
   patMuonNeHadSumPt05_ = 0;
   patMuonGamSumPt05_ = 0;
   fastJetRho_ = 0;
   PFchsJetRho_ = 0;
   lepIsoRho_ = 0;
   patElecEt_ = 0;
   patElecEnergy_ = 0;
   patElecPt_ = 0;
   patElecEta_ = 0;
   patElecPhi_ = 0;
   patElecM_ = 0;
   patElecScEn_ = 0;
   patElecScEt_ = 0;
   patElecScEta_ = 0;
   patElecScPhi_ = 0;
   patElecisEcalDriven_ = 0;
   patElecisTrackerDriven_ = 0;
   patElecSigIhIh_ = 0;
   patElecDelEtaIn_ = 0;
   patElecDelPhiIn_ = 0;
   patElecHoE_ = 0;
   patElecTrkIso_ = 0;
   patElecHcalIso_ = 0;
   patElecEcalIso_ = 0;
   patElecCharge_ = 0;
   patElecRelIsoComb_ = 0;
   patElecDxy_ = 0;
   patElecD0_ = 0;
   patElecDsz_ = 0;
   patElecDz_ = 0;
   patElecDxyBS_ = 0;
   patElecDszBS_ = 0;
   patElecDzBS_ = 0;
   patElecMva_ = 0;
   patElecChHadSumPt03_ = 0;
   patElecNeHadSumPt03_ = 0;
   patElecGamSumPt03_ = 0;
   patElecChHadSumPt04_ = 0;
   patElecChHadIso_ = 0;
   patElecNeHadIso_ = 0;
   patElecGamIso_ = 0;
   patElecNeHadSumPt04_ = 0;
   patElecGamSumPt04_ = 0;
   patElecChHadSumPt05_ = 0;
   patElecNeHadSumPt05_ = 0;
   patElecGamSumPt05_ = 0;
   patElecMissingHits_ = 0;
   patElecDist_ = 0;
   patElecDeltaCotTheta_ = 0;
   patElecConvRadius_ = 0;
   patElecInBarrel_ = 0;
   patElecInEndcap_ = 0;
   JetPt_ = 0;
   JetEta_ = 0;
   JetPhi_ = 0;
   JetM_ = 0;
   JetEn_ = 0;
   JetCharMulti_ = 0;
   JetNeutEmEFr_ = 0;
   JetCharHadEFr_ = 0;
   JetNeutHadEFr_ = 0;
   JetCharEmEFr_ = 0;
   higgsPt = 0;
   higgsEta = 0;
   higgsPhi = 0;
   higgsM = 0;
   higgsMRefit = 0;
   zllPt = 0;
   zllEta = 0;
   zllPhi = 0;
   zllM = 0;
   zlldR = 0;
   zjjPt = 0;
   zjjEta = 0;
   zjjPhi = 0;
   zjjM = 0;
   zjjMRefit = 0;
   zjjdR = 0;
   HjetIndex = 0;
   HjetHiggsIndex_ = 0;
   HjetE = 0;
   HjetPt = 0;
   HjetEta = 0;
   HjetPhi = 0;
   LeptonsIndex = 0;
   LeptonsHiggsIndex_ = 0;
   LeptonsE = 0;
   LeptonsPt = 0;
   LeptonsEta = 0;
   LeptonsPhi = 0;
   LeptonsType = 0;
   heliLD = 0;
   costhetaNT1 = 0;
   costhetaNT2 = 0;
   phiNT = 0;
   phiNT1 = 0;
   costhetastarNT = 0;
   heliLDRefit = 0;
   costhetaNT1Refit = 0;
   costhetaNT2Refit = 0;
   phiNTRefit = 0;
   phiNT1Refit = 0;
   costhetastarNTRefit = 0;
   nBTags = 0;
   lepType = 0;
   passBit = 0;


 JetNConstituents_ = 0;
   JetGenPartonID_ = 0;
   JetGenPartonEn_ = 0;
   JetGenPartonPt_ = 0;
   JetGenPartonEta_ = 0;
   JetGenPartonPhi_ = 0;
   JetGenPartonStatus_ = 0;
   JetGenPartonU3ID_ = 0;
   JetGenPartonU2ID_ = 0;
   JetGenPartonU1ID_ = 0;
   JethasGenParton_=0;
   
   patElecID_=0;
   patMuonID_=0;




 

   Analysis->SetBranchAddress("PU_nTrueInt", &PU_nTrueInt);
   Analysis->SetBranchAddress("PU_nPUVert", &PU_nPUVert);
   Analysis->SetBranchAddress("EvtInfo_EventNum", &EvtInfo_EventNum);
   Analysis->SetBranchAddress("EvtInfo_RunNum", &EvtInfo_RunNum);
   Analysis->SetBranchAddress("EvtInfo_LumiSection", &EvtInfo_LumiSection);
   Analysis->SetBranchAddress("EvtInfo_BunchXing", &EvtInfo_BunchXing);
   Analysis->SetBranchAddress("EvtInfo_NumVtx", &EvtInfo_NumVtx);
   Analysis->SetBranchAddress("EvtInfo_VertexX_", &EvtInfo_VertexX_);
   Analysis->SetBranchAddress("EvtInfo_VertexY_", &EvtInfo_VertexY_);
   Analysis->SetBranchAddress("EvtInfo_VertexZ_", &EvtInfo_VertexZ_);
   Analysis->SetBranchAddress("ptHat_", &ptHat_);
   Analysis->SetBranchAddress("mcWeight_", &mcWeight_);
   Analysis->SetBranchAddress("genParE_", &genParE_);
   Analysis->SetBranchAddress("genParPt_", &genParPt_);
   Analysis->SetBranchAddress("genParEta_", &genParEta_);
   Analysis->SetBranchAddress("genParPhi_", &genParPhi_);
   Analysis->SetBranchAddress("genParM_", &genParM_);
   Analysis->SetBranchAddress("genParQ_", &genParQ_);
   Analysis->SetBranchAddress("genParId_", &genParId_);
   Analysis->SetBranchAddress("genParSt_", &genParSt_);
   Analysis->SetBranchAddress("genMomParId_", &genMomParId_);
   Analysis->SetBranchAddress("genParIndex_", &genParIndex_);
   Analysis->SetBranchAddress("genNMo_", &genNMo_);
   Analysis->SetBranchAddress("genNDa_", &genNDa_);
   Analysis->SetBranchAddress("genMo1_", &genMo1_);
   Analysis->SetBranchAddress("genMo2_", &genMo2_);
   Analysis->SetBranchAddress("genDa1_", &genDa1_);
   Analysis->SetBranchAddress("genDa2_", &genDa2_);
   Analysis->SetBranchAddress("genJetE_", &genJetE_);
   Analysis->SetBranchAddress("genJetPt_", &genJetPt_);
   Analysis->SetBranchAddress("genJetEta_", &genJetEta_);
   Analysis->SetBranchAddress("genJetPhi_", &genJetPhi_);
   Analysis->SetBranchAddress("NumMu", &NumMu);
   Analysis->SetBranchAddress("patMuonPt_", &patMuonPt_);
   Analysis->SetBranchAddress("patMuonEta_", &patMuonEta_);
   Analysis->SetBranchAddress("patMuonPhi_", &patMuonPhi_);
   Analysis->SetBranchAddress("patMuonM_", &patMuonM_);
   Analysis->SetBranchAddress("patMuonSumTrkPt_", &patMuonSumTrkPt_);
   Analysis->SetBranchAddress("patMuonTrkIso_", &patMuonTrkIso_);
   Analysis->SetBranchAddress("patMuonHcalIso_", &patMuonHcalIso_);
   Analysis->SetBranchAddress("patMuonEcalIso_", &patMuonEcalIso_);
   Analysis->SetBranchAddress("patMuonCharge_", &patMuonCharge_);
   Analysis->SetBranchAddress("patMuonNumChambers_", &patMuonNumChambers_);
   Analysis->SetBranchAddress("patMuonNumMatches_", &patMuonNumMatches_);
   Analysis->SetBranchAddress("patMuonStationMask_", &patMuonStationMask_);
   Analysis->SetBranchAddress("patMuonNumSegments_", &patMuonNumSegments_);
   Analysis->SetBranchAddress("patMuonChi2Ndoff_", &patMuonChi2Ndoff_);
   Analysis->SetBranchAddress("patMuonNhits_", &patMuonNhits_);
   Analysis->SetBranchAddress("patMuonQoverP_", &patMuonQoverP_);
   Analysis->SetBranchAddress("patMuonTheta_", &patMuonTheta_);
   Analysis->SetBranchAddress("patMuonLambda_", &patMuonLambda_);
   Analysis->SetBranchAddress("patMuonDxy_", &patMuonDxy_);
   Analysis->SetBranchAddress("patMuonD0_", &patMuonD0_);
   Analysis->SetBranchAddress("patMuonDsz_", &patMuonDsz_);
   Analysis->SetBranchAddress("patMuonDs_", &patMuonDs_);
   Analysis->SetBranchAddress("patMuonDxyBS_", &patMuonDxyBS_);
   Analysis->SetBranchAddress("patMuonDzBS_", &patMuonDzBS_);
   Analysis->SetBranchAddress("patMuonDszBS_", &patMuonDszBS_);
   Analysis->SetBranchAddress("patMuonVx_", &patMuonVx_);
   Analysis->SetBranchAddress("patMuonVy_", &patMuonVy_);
   Analysis->SetBranchAddress("patMuonVz_", &patMuonVz_);
   Analysis->SetBranchAddress("patMuonGenMatchPt_", &patMuonGenMatchPt_);
   Analysis->SetBranchAddress("patMuonGenMatchEta_", &patMuonGenMatchEta_);
   Analysis->SetBranchAddress("patMuonGenMatchPhi_", &patMuonGenMatchPhi_);
   Analysis->SetBranchAddress("patMuonGenMotherId_", &patMuonGenMotherId_);
   Analysis->SetBranchAddress("patMuonGenMatchCharge_", &patMuonGenMatchCharge_);
   Analysis->SetBranchAddress("patMuonChHadSumPt03_", &patMuonChHadSumPt03_);
   Analysis->SetBranchAddress("patMuonNeHadSumPt03_", &patMuonNeHadSumPt03_);
   Analysis->SetBranchAddress("patMuonGamSumPt03_", &patMuonGamSumPt03_);
   Analysis->SetBranchAddress("patMuonChHadSumPt04_", &patMuonChHadSumPt04_);
   Analysis->SetBranchAddress("patMuonNeHadSumPt04_", &patMuonNeHadSumPt04_);
   Analysis->SetBranchAddress("patMuonGamSumPt04_", &patMuonGamSumPt04_);
   Analysis->SetBranchAddress("patMuonChHadSumPt05_", &patMuonChHadSumPt05_);
   Analysis->SetBranchAddress("patMuonNeHadSumPt05_", &patMuonNeHadSumPt05_);
   Analysis->SetBranchAddress("patMuonGamSumPt05_", &patMuonGamSumPt05_);
   Analysis->SetBranchAddress("fastJetRho_", &fastJetRho_);
   Analysis->SetBranchAddress("PFchsJetRho_", &PFchsJetRho_);
   Analysis->SetBranchAddress("lepIsoRho_", &lepIsoRho_);
   Analysis->SetBranchAddress("patElecEt_", &patElecEt_);
   Analysis->SetBranchAddress("patElecEnergy_", &patElecEnergy_);
   Analysis->SetBranchAddress("patElecPt_", &patElecPt_);
   Analysis->SetBranchAddress("patElecEta_", &patElecEta_);
   Analysis->SetBranchAddress("patElecPhi_", &patElecPhi_);
   Analysis->SetBranchAddress("patElecM_", &patElecM_);
   Analysis->SetBranchAddress("patElecScEn_", &patElecScEn_);
   Analysis->SetBranchAddress("patElecScEt_", &patElecScEt_);
   Analysis->SetBranchAddress("patElecScEta_", &patElecScEta_);
   Analysis->SetBranchAddress("patElecScPhi_", &patElecScPhi_);
   Analysis->SetBranchAddress("patElecisEcalDriven_", &patElecisEcalDriven_);
   Analysis->SetBranchAddress("patElecisTrackerDriven_", &patElecisTrackerDriven_);
   Analysis->SetBranchAddress("patElecSigIhIh_", &patElecSigIhIh_);
   Analysis->SetBranchAddress("patElecDelEtaIn_", &patElecDelEtaIn_);
   Analysis->SetBranchAddress("patElecDelPhiIn_", &patElecDelPhiIn_);
   Analysis->SetBranchAddress("patElecHoE_", &patElecHoE_);
   Analysis->SetBranchAddress("patElecTrkIso_", &patElecTrkIso_);
   Analysis->SetBranchAddress("patElecHcalIso_", &patElecHcalIso_);
   Analysis->SetBranchAddress("patElecEcalIso_", &patElecEcalIso_);
   Analysis->SetBranchAddress("patElecCharge_", &patElecCharge_);
   Analysis->SetBranchAddress("patElecRelIsoComb_", &patElecRelIsoComb_);
   Analysis->SetBranchAddress("patElecDxy_", &patElecDxy_);
   Analysis->SetBranchAddress("patElecD0_", &patElecD0_);
   Analysis->SetBranchAddress("patElecDsz_", &patElecDsz_);
   Analysis->SetBranchAddress("patElecDz_", &patElecDz_);
   Analysis->SetBranchAddress("patElecDxyBS_", &patElecDxyBS_);
   Analysis->SetBranchAddress("patElecDszBS_", &patElecDszBS_);
   Analysis->SetBranchAddress("patElecDzBS_", &patElecDzBS_);
   Analysis->SetBranchAddress("patElecMva_", &patElecMva_);
   Analysis->SetBranchAddress("patElecChHadSumPt03_", &patElecChHadSumPt03_);
   Analysis->SetBranchAddress("patElecNeHadSumPt03_", &patElecNeHadSumPt03_);
   Analysis->SetBranchAddress("patElecGamSumPt03_", &patElecGamSumPt03_);
   Analysis->SetBranchAddress("patElecChHadSumPt04_", &patElecChHadSumPt04_);
   Analysis->SetBranchAddress("patElecChHadIso_", &patElecChHadIso_);
   Analysis->SetBranchAddress("patElecNeHadIso_", &patElecNeHadIso_);
   Analysis->SetBranchAddress("patElecGamIso_", &patElecGamIso_);
   Analysis->SetBranchAddress("patElecNeHadSumPt04_", &patElecNeHadSumPt04_);
   Analysis->SetBranchAddress("patElecGamSumPt04_", &patElecGamSumPt04_);
   Analysis->SetBranchAddress("patElecChHadSumPt05_", &patElecChHadSumPt05_);
   Analysis->SetBranchAddress("patElecNeHadSumPt05_", &patElecNeHadSumPt05_);
   Analysis->SetBranchAddress("patElecGamSumPt05_", &patElecGamSumPt05_);
   Analysis->SetBranchAddress("patElecMissingHits_", &patElecMissingHits_);
   Analysis->SetBranchAddress("patElecDist_", &patElecDist_);
   Analysis->SetBranchAddress("patElecDeltaCotTheta_", &patElecDeltaCotTheta_);
   Analysis->SetBranchAddress("patElecConvRadius_", &patElecConvRadius_);
   Analysis->SetBranchAddress("patElecInBarrel_", &patElecInBarrel_);
   Analysis->SetBranchAddress("patElecInEndcap_", &patElecInEndcap_);
   Analysis->SetBranchAddress("JetPt_", &JetPt_);
   Analysis->SetBranchAddress("JetEta_", &JetEta_);
   Analysis->SetBranchAddress("JetPhi_", &JetPhi_);
   Analysis->SetBranchAddress("JetM_", &JetM_);
   Analysis->SetBranchAddress("JetEn_", &JetEn_);
   Analysis->SetBranchAddress("JetCharMulti_", &JetCharMulti_);
   Analysis->SetBranchAddress("JetNeutEmEFr_", &JetNeutEmEFr_);
   Analysis->SetBranchAddress("JetCharHadEFr_", &JetCharHadEFr_);
   Analysis->SetBranchAddress("JetNeutHadEFr_", &JetNeutHadEFr_);
   Analysis->SetBranchAddress("JetCharEmEFr_", &JetCharEmEFr_);
   Analysis->SetBranchAddress("eleRho", &eleRho);
   Analysis->SetBranchAddress("muoRho", &muoRho);
   Analysis->SetBranchAddress("metSig", &metSig);
   Analysis->SetBranchAddress("higgsPt", &higgsPt);
   Analysis->SetBranchAddress("higgsEta", &higgsEta);
   Analysis->SetBranchAddress("higgsPhi", &higgsPhi);
   Analysis->SetBranchAddress("higgsM", &higgsM);
   Analysis->SetBranchAddress("higgsMRefit", &higgsMRefit);
   Analysis->SetBranchAddress("zllPt", &zllPt);
   Analysis->SetBranchAddress("zllEta", &zllEta);
   Analysis->SetBranchAddress("zllPhi", &zllPhi);
   Analysis->SetBranchAddress("zllM", &zllM);
   Analysis->SetBranchAddress("zlldR", &zlldR);
   Analysis->SetBranchAddress("zjjPt", &zjjPt);
   Analysis->SetBranchAddress("zjjEta", &zjjEta);
   Analysis->SetBranchAddress("zjjPhi", &zjjPhi);
   Analysis->SetBranchAddress("zjjM", &zjjM);
   Analysis->SetBranchAddress("zjjMRefit", &zjjMRefit);
   Analysis->SetBranchAddress("zjjdR", &zjjdR);
   Analysis->SetBranchAddress("HjetIndex", &HjetIndex);
   Analysis->SetBranchAddress("HjetHiggsIndex_", &HjetHiggsIndex_);
   Analysis->SetBranchAddress("HjetE", &HjetE);
   Analysis->SetBranchAddress("HjetPt", &HjetPt);
   Analysis->SetBranchAddress("HjetEta", &HjetEta);
   Analysis->SetBranchAddress("HjetPhi", &HjetPhi);
   Analysis->SetBranchAddress("LeptonsIndex", &LeptonsIndex);
   Analysis->SetBranchAddress("LeptonsHiggsIndex_", &LeptonsHiggsIndex_);
   Analysis->SetBranchAddress("LeptonsE", &LeptonsE);
   Analysis->SetBranchAddress("LeptonsPt", &LeptonsPt);
   Analysis->SetBranchAddress("LeptonsEta", &LeptonsEta);
   Analysis->SetBranchAddress("LeptonsPhi", &LeptonsPhi);
   Analysis->SetBranchAddress("LeptonsType", &LeptonsType);
   Analysis->SetBranchAddress("heliLD", &heliLD);
   Analysis->SetBranchAddress("costhetaNT1", &costhetaNT1);
   Analysis->SetBranchAddress("costhetaNT2", &costhetaNT2);
   Analysis->SetBranchAddress("phiNT", &phiNT);
   Analysis->SetBranchAddress("phiNT1", &phiNT1);
   Analysis->SetBranchAddress("costhetastarNT", &costhetastarNT);
   Analysis->SetBranchAddress("heliLDRefit", &heliLDRefit);
   Analysis->SetBranchAddress("costhetaNT1Refit", &costhetaNT1Refit);
   Analysis->SetBranchAddress("costhetaNT2Refit", &costhetaNT2Refit);
   Analysis->SetBranchAddress("phiNTRefit", &phiNTRefit);
   Analysis->SetBranchAddress("phiNT1Refit", &phiNT1Refit);
   Analysis->SetBranchAddress("costhetastarNTRefit", &costhetastarNTRefit);
   Analysis->SetBranchAddress("nBTags", &nBTags);
   Analysis->SetBranchAddress("lepType", &lepType);
   Analysis->SetBranchAddress("passBit", &passBit);

 Analysis->SetBranchAddress("JetNConstituents_", &JetNConstituents_);
   Analysis->SetBranchAddress("JetGenPartonID_", &JetGenPartonID_ );
   Analysis->SetBranchAddress("JetGenPartonEn_", &JetGenPartonEn_ );
   Analysis->SetBranchAddress("JetGenPartonPt_", &JetGenPartonPt_ );
   Analysis->SetBranchAddress("JetGenPartonEta_", &JetGenPartonEta_);
   Analysis->SetBranchAddress("JetGenPartonPhi_", &JetGenPartonPhi_);
   Analysis->SetBranchAddress("JetGenPartonStatus_", &JetGenPartonStatus_);
   Analysis->SetBranchAddress("JetGenPartonU3ID_", &JetGenPartonU3ID_);
   Analysis->SetBranchAddress("JetGenPartonU2ID_", &JetGenPartonU2ID_);
   Analysis->SetBranchAddress("JetGenPartonU1ID_", &JetGenPartonU1ID_);

   Analysis->SetBranchAddress("JethasGenParton_",&JethasGenParton_);
   
   Analysis->SetBranchAddress("patMuonID_",&patMuonID_);
   Analysis->SetBranchAddress("patElecID_",&patElecID_);












   }//func Register
};
